/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedMeusIngressosRouteImport } from './routes/_authenticated/meus-ingressos'
import { Route as AuthenticatedOrganizadorRouteImport } from './routes/_authenticated/organizador'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as AuthenticatedOrganizadorIndexRouteImport } from './routes/_authenticated/organizador.index'
import { Route as AuthenticatedValidacaoIndexRouteImport } from './routes/_authenticated/validacao.index'
import { Route as AuthenticatedOrganizadorEventosNovoRouteImport } from './routes/_authenticated/organizador.eventos.novo'
import { Route as AuthenticatedValidacaoEventIdScannerRouteImport } from './routes/_authenticated/validacao.$eventId.scanner'
import { Route as AuthenticatedOrganizadorEventosIdDashboardRouteImport } from './routes/_authenticated/organizador.eventos.$id.dashboard'
import { Route as AuthenticatedOrganizadorEventosIdEditarRouteImport } from './routes/_authenticated/organizador.eventos.$id.editar'
import { Route as AuthenticatedOrganizadorEventosIdEquipeRouteImport } from './routes/_authenticated/organizador.eventos.$id.equipe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusIngressosRoute =
  AuthenticatedMeusIngressosRouteImport.update({
    id: '/meus-ingressos',
    path: '/meus-ingressos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizadorRoute =
  AuthenticatedOrganizadorRouteImport.update({
    id: '/organizador',
    path: '/organizador',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizadorIndexRoute =
  AuthenticatedOrganizadorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizadorRoute,
  } as any)
const AuthenticatedValidacaoIndexRoute =
  AuthenticatedValidacaoIndexRouteImport.update({
    id: '/validacao/',
    path: '/validacao/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizadorEventosNovoRoute =
  AuthenticatedOrganizadorEventosNovoRouteImport.update({
    id: '/eventos/novo',
    path: '/eventos/novo',
    getParentRoute: () => AuthenticatedOrganizadorRoute,
  } as any)
const AuthenticatedValidacaoEventIdScannerRoute =
  AuthenticatedValidacaoEventIdScannerRouteImport.update({
    id: '/validacao/$eventId/scanner',
    path: '/validacao/$eventId/scanner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizadorEventosIdDashboardRoute =
  AuthenticatedOrganizadorEventosIdDashboardRouteImport.update({
    id: '/eventos/$id/dashboard',
    path: '/eventos/$id/dashboard',
    getParentRoute: () => AuthenticatedOrganizadorRoute,
  } as any)
const AuthenticatedOrganizadorEventosIdEditarRoute =
  AuthenticatedOrganizadorEventosIdEditarRouteImport.update({
    id: '/eventos/$id/editar',
    path: '/eventos/$id/editar',
    getParentRoute: () => AuthenticatedOrganizadorRoute,
  } as any)
const AuthenticatedOrganizadorEventosIdEquipeRoute =
  AuthenticatedOrganizadorEventosIdEquipeRouteImport.update({
    id: '/eventos/$id/equipe',
    path: '/eventos/$id/equipe',
    getParentRoute: () => AuthenticatedOrganizadorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/organizador': typeof AuthenticatedOrganizadorRouteWithChildren
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/organizador/': typeof AuthenticatedOrganizadorIndexRoute
  '/validacao/': typeof AuthenticatedValidacaoIndexRoute
  '/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/validacao/$eventId/scanner': typeof AuthenticatedValidacaoEventIdScannerRoute
  '/organizador/eventos/$id/dashboard': typeof AuthenticatedOrganizadorEventosIdDashboardRoute
  '/organizador/eventos/$id/editar': typeof AuthenticatedOrganizadorEventosIdEditarRoute
  '/organizador/eventos/$id/equipe': typeof AuthenticatedOrganizadorEventosIdEquipeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/organizador': typeof AuthenticatedOrganizadorIndexRoute
  '/validacao': typeof AuthenticatedValidacaoIndexRoute
  '/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/validacao/$eventId/scanner': typeof AuthenticatedValidacaoEventIdScannerRoute
  '/organizador/eventos/$id/dashboard': typeof AuthenticatedOrganizadorEventosIdDashboardRoute
  '/organizador/eventos/$id/editar': typeof AuthenticatedOrganizadorEventosIdEditarRoute
  '/organizador/eventos/$id/equipe': typeof AuthenticatedOrganizadorEventosIdEquipeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/meus-ingressos': typeof AuthenticatedMeusIngressosRoute
  '/_authenticated/organizador': typeof AuthenticatedOrganizadorRouteWithChildren
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/_authenticated/organizador/': typeof AuthenticatedOrganizadorIndexRoute
  '/_authenticated/validacao/': typeof AuthenticatedValidacaoIndexRoute
  '/_authenticated/organizador/eventos/novo': typeof AuthenticatedOrganizadorEventosNovoRoute
  '/_authenticated/validacao/$eventId/scanner': typeof AuthenticatedValidacaoEventIdScannerRoute
  '/_authenticated/organizador/eventos/$id/dashboard': typeof AuthenticatedOrganizadorEventosIdDashboardRoute
  '/_authenticated/organizador/eventos/$id/editar': typeof AuthenticatedOrganizadorEventosIdEditarRoute
  '/_authenticated/organizador/eventos/$id/equipe': typeof AuthenticatedOrganizadorEventosIdEquipeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/meus-ingressos'
    | '/organizador'
    | '/checkout/$orderId'
    | '/eventos/$slug'
    | '/organizador/'
    | '/validacao/'
    | '/organizador/eventos/novo'
    | '/validacao/$eventId/scanner'
    | '/organizador/eventos/$id/dashboard'
    | '/organizador/eventos/$id/editar'
    | '/organizador/eventos/$id/equipe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/meus-ingressos'
    | '/checkout/$orderId'
    | '/eventos/$slug'
    | '/organizador'
    | '/validacao'
    | '/organizador/eventos/novo'
    | '/validacao/$eventId/scanner'
    | '/organizador/eventos/$id/dashboard'
    | '/organizador/eventos/$id/editar'
    | '/organizador/eventos/$id/equipe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/meus-ingressos'
    | '/_authenticated/organizador'
    | '/checkout/$orderId'
    | '/eventos/$slug'
    | '/_authenticated/organizador/'
    | '/_authenticated/validacao/'
    | '/_authenticated/organizador/eventos/novo'
    | '/_authenticated/validacao/$eventId/scanner'
    | '/_authenticated/organizador/eventos/$id/dashboard'
    | '/_authenticated/organizador/eventos/$id/editar'
    | '/_authenticated/organizador/eventos/$id/equipe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  EventosSlugRoute: typeof EventosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-ingressos': {
      id: '/_authenticated/meus-ingressos'
      path: '/meus-ingressos'
      fullPath: '/meus-ingressos'
      preLoaderRoute: typeof AuthenticatedMeusIngressosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizador': {
      id: '/_authenticated/organizador'
      path: '/organizador'
      fullPath: '/organizador'
      preLoaderRoute: typeof AuthenticatedOrganizadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizador/': {
      id: '/_authenticated/organizador/'
      path: '/'
      fullPath: '/organizador/'
      preLoaderRoute: typeof AuthenticatedOrganizadorIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizadorRoute
    }
    '/_authenticated/validacao/': {
      id: '/_authenticated/validacao/'
      path: '/validacao'
      fullPath: '/validacao/'
      preLoaderRoute: typeof AuthenticatedValidacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizador/eventos/novo': {
      id: '/_authenticated/organizador/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/organizador/eventos/novo'
      preLoaderRoute: typeof AuthenticatedOrganizadorEventosNovoRouteImport
      parentRoute: typeof AuthenticatedOrganizadorRoute
    }
    '/_authenticated/validacao/$eventId/scanner': {
      id: '/_authenticated/validacao/$eventId/scanner'
      path: '/validacao/$eventId/scanner'
      fullPath: '/validacao/$eventId/scanner'
      preLoaderRoute: typeof AuthenticatedValidacaoEventIdScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizador/eventos/$id/dashboard': {
      id: '/_authenticated/organizador/eventos/$id/dashboard'
      path: '/eventos/$id/dashboard'
      fullPath: '/organizador/eventos/$id/dashboard'
      preLoaderRoute: typeof AuthenticatedOrganizadorEventosIdDashboardRouteImport
      parentRoute: typeof AuthenticatedOrganizadorRoute
    }
    '/_authenticated/organizador/eventos/$id/editar': {
      id: '/_authenticated/organizador/eventos/$id/editar'
      path: '/eventos/$id/editar'
      fullPath: '/organizador/eventos/$id/editar'
      preLoaderRoute: typeof AuthenticatedOrganizadorEventosIdEditarRouteImport
      parentRoute: typeof AuthenticatedOrganizadorRoute
    }
    '/_authenticated/organizador/eventos/$id/equipe': {
      id: '/_authenticated/organizador/eventos/$id/equipe'
      path: '/eventos/$id/equipe'
      fullPath: '/organizador/eventos/$id/equipe'
      preLoaderRoute: typeof AuthenticatedOrganizadorEventosIdEquipeRouteImport
      parentRoute: typeof AuthenticatedOrganizadorRoute
    }
  }
}

interface AuthenticatedOrganizadorRouteChildren {
  AuthenticatedOrganizadorIndexRoute: typeof AuthenticatedOrganizadorIndexRoute
  AuthenticatedOrganizadorEventosNovoRoute: typeof AuthenticatedOrganizadorEventosNovoRoute
  AuthenticatedOrganizadorEventosIdDashboardRoute: typeof AuthenticatedOrganizadorEventosIdDashboardRoute
  AuthenticatedOrganizadorEventosIdEditarRoute: typeof AuthenticatedOrganizadorEventosIdEditarRoute
  AuthenticatedOrganizadorEventosIdEquipeRoute: typeof AuthenticatedOrganizadorEventosIdEquipeRoute
}

const AuthenticatedOrganizadorRouteChildren: AuthenticatedOrganizadorRouteChildren =
  {
    AuthenticatedOrganizadorIndexRoute: AuthenticatedOrganizadorIndexRoute,
    AuthenticatedOrganizadorEventosNovoRoute:
      AuthenticatedOrganizadorEventosNovoRoute,
    AuthenticatedOrganizadorEventosIdDashboardRoute:
      AuthenticatedOrganizadorEventosIdDashboardRoute,
    AuthenticatedOrganizadorEventosIdEditarRoute:
      AuthenticatedOrganizadorEventosIdEditarRoute,
    AuthenticatedOrganizadorEventosIdEquipeRoute:
      AuthenticatedOrganizadorEventosIdEquipeRoute,
  }

const AuthenticatedOrganizadorRouteWithChildren =
  AuthenticatedOrganizadorRoute._addFileChildren(
    AuthenticatedOrganizadorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMeusIngressosRoute: typeof AuthenticatedMeusIngressosRoute
  AuthenticatedOrganizadorRoute: typeof AuthenticatedOrganizadorRouteWithChildren
  AuthenticatedValidacaoIndexRoute: typeof AuthenticatedValidacaoIndexRoute
  AuthenticatedValidacaoEventIdScannerRoute: typeof AuthenticatedValidacaoEventIdScannerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeusIngressosRoute: AuthenticatedMeusIngressosRoute,
  AuthenticatedOrganizadorRoute: AuthenticatedOrganizadorRouteWithChildren,
  AuthenticatedValidacaoIndexRoute: AuthenticatedValidacaoIndexRoute,
  AuthenticatedValidacaoEventIdScannerRoute:
    AuthenticatedValidacaoEventIdScannerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  EventosSlugRoute: EventosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
